config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  post 'create_users' => 'welcome#users'
  get 'users' => 'welcome#users'
  
  post 'products' => 'welcome#create_products'
  get 'products' => 'welcome#products'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  	@product = Product.new
  end

  # def create_users
  # 	user = User.create(name: params[:name], age: params[:age])
  # 	redirect_to users_path
  # end

  def users
  	unless params[:name] == nil
    	@user = User.create(name: params[:name], age: params[:age])
  	end

  	@users = User.all
  end

  def create_products
  	product = Product.create(product_params)
  	redirect_to products_path
  end

  def products
  	@products = Product.all
  end

  private

	  def product_params
	  	params.require(:product).permit(:name, :price, :quantity)
	  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NoScaffolds</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Home Page</h1>

<div style="margin:50px">
	<h3>Create a User</h3>
	<%= form_tag create_users_path do %>
		<%= text_field_tag :name, nil, placeholder: "Your Name" %><br>
		<%= number_field_tag :age, nil, placeholder: "Your Age" %><br>
    <%= submit_tag "Create Profile" %>
	<% end %>
</div>

<%= link_to "All Users", users_path %>

<div style="margin:50px;">
  <h3>Create a Product</h3>
  <%= form_for @product do |f| %>
		<%= f.text_field :name, placeholder: "Product Name" %><br />
		<%= f.number_field :price, placeholder: "Price", step: :any %><br />
		<%= f.number_field :quantity, placeholder: "Quantity" %><br />
		<%= f.submit %>
  <% end %>
</div>

<%= link_to "All Products", products_path %>

app/views/welcome/products.html.erb
<h1>Here is a list of all products:</h1>

<table border="2">
  <tr>
    <th>Name</th>
		<th>Price</th>
    <th>Quantity</th>
  </tr>

  <% @products.each do |product| %>
    <tr>
      <td><%= product.name %></td>
      <td><%= number_to_currency product.price %></td>
	    <td><%= product.quantity %></td>
		</tr>
  <% end %>
</table>

<p>
	<%= link_to "Return to Index", root_path %>
</p>

app/views/welcome/users.html.erb
<h1>Here is a list of all users:</h1>

<table border="2">
	<tr>
		<th>Name</th>
		<th>Age</th>
	</tr>

	<% @users.each do |user| %>
		<tr>
			<td><%= user.name %></td>
			<td><%= user.age %></td>
		</tr>
	<% end %>
</table>

<p>
	<%= link_to "Return to Index", root_path %>
</p>